-- =========================
-- DROP TABLES (ORDEN CORRECTO)
-- =========================

USE RAW_DATA_ALCANTARA

DROP TABLE IF EXISTS FACT_ASISTENCIA;
DROP TABLE IF EXISTS FACT_CALIFICACION;
DROP TABLE IF EXISTS FACT_MATRICULA;

DROP TABLE IF EXISTS DIM_CALENDARIO;
DROP TABLE IF EXISTS DIM_SEMESTRE;
DROP TABLE IF EXISTS DIM_CURSO;
DROP TABLE IF EXISTS DIM_ASIGNATURA;
DROP TABLE IF EXISTS DIM_DOCENTE;
DROP TABLE IF EXISTS DIM_ALUMNO;
DROP TABLE IF EXISTS DIM_COLEGIO;

-- =========================
-- DIMENSIONES
-- =========================

CREATE TABLE DIM_COLEGIO (
      COLEGIO_KEY INT PRIMARY KEY IDENTITY(1,1)
    , NOMBRE_COLEGIO NVARCHAR(255) DEFAULT '?'
    , DIRECCION_COLEGIO NVARCHAR(255) DEFAULT '?'
    , COMUNA_COLEGIO NVARCHAR(255) DEFAULT '?'
);

CREATE TABLE DIM_ALUMNO (
      ALUMNO_KEY INT PRIMARY KEY IDENTITY(1,1)
    , RUT_ALUMNO NVARCHAR(255) DEFAULT '?'
    , NOMBRES NVARCHAR(255) DEFAULT '?'
    , APELLIDO_PATERNO NVARCHAR(255) DEFAULT '?'
    , APELLIDO_MATERNO NVARCHAR(255) DEFAULT '?'
    , FECHA_NACIMIENTO NVARCHAR(255) DEFAULT '1900-01-01 00:00:00.000'
    , GENERO NVARCHAR(255) DEFAULT '?'
);

CREATE TABLE DIM_DOCENTE (
      DOCENTE_KEY INT PRIMARY KEY IDENTITY(1,1)
    , RUT_DOCENTE NVARCHAR(255) DEFAULT '?'
    , NOMBRES NVARCHAR(255) DEFAULT '?'
    , APELLIDO_PATERNO NVARCHAR(255) DEFAULT '?'
    , APELLIDO_MATERNO NVARCHAR(255) DEFAULT '?'
    , ESPECIALIDAD NVARCHAR(255) DEFAULT '?'
);

CREATE TABLE DIM_ASIGNATURA (
      ASIGNATURA_KEY INT PRIMARY KEY IDENTITY(1,1)
    , NOMBRE_ASIGNATURA NVARCHAR(255) DEFAULT '?'
    , AREA_CONOCIMIENTO NVARCHAR(255) DEFAULT '?'
);

CREATE TABLE DIM_CURSO (
      CURSO_KEY INT PRIMARY KEY IDENTITY(1,1)
    , NOMBRE_CURSO NVARCHAR(255) DEFAULT '?'
    , NIVEL_EDUCATIVO NVARCHAR(255) DEFAULT '?'
);

CREATE TABLE DIM_SEMESTRE (
      SEMESTRE_KEY INT PRIMARY KEY IDENTITY(1,1)
    , NOMBRE_SEMESTRE NVARCHAR(255) DEFAULT '?'
    , ANIO_ACADEMICO INT DEFAULT 0
);

CREATE TABLE [dbo].[DIM_CALENDARIO] (
      [CALENDARIO_KEY] INT PRIMARY KEY -- 
    , [FECHA_COMPLETA] DATE DEFAULT '1900-01-01' -- 
    , [DIA_SEMANA] VARCHAR(15) DEFAULT '?'
    , [DIA_MES] INT DEFAULT 0
    , [MES_NOMBRE] VARCHAR(15) DEFAULT '?'
    , [MES_NUMERO] INT DEFAULT 0 -- 
    , [ANIO] INT DEFAULT 0
    , [ES_FERIADO] BIT DEFAULT 0
    , [ES_DIA_HABIL] BIT DEFAULT 1
);

-- =========================
-- FACTS
-- =========================

CREATE TABLE FACT_MATRICULA (
      MATRICULA_KEY INT PRIMARY KEY IDENTITY(1,1)
    , COLEGIO_KEY INT
    , ALUMNO_KEY INT
    , ALUMNO_RUT VARCHAR(12) DEFAULT '?' 
    , CURSO_KEY INT
    , NIVEL INT
    , CURSO_DETALLE CHAR(2)
    , CALENDARIO_KEY INT
    , MONTO_MATRICULA DECIMAL(18,2) DEFAULT 0.00

    , CONSTRAINT FK_MATRICULA_COLEGIO FOREIGN KEY (COLEGIO_KEY) REFERENCES DIM_COLEGIO(COLEGIO_KEY)
    , CONSTRAINT FK_MATRICULA_ALUMNO FOREIGN KEY (ALUMNO_KEY) REFERENCES DIM_ALUMNO(ALUMNO_KEY)
    , CONSTRAINT FK_MATRICULA_CURSO FOREIGN KEY (CURSO_KEY) REFERENCES DIM_CURSO(CURSO_KEY)
    , CONSTRAINT FK_MATRICULA_CALENDARIO FOREIGN KEY (CALENDARIO_KEY) REFERENCES DIM_CALENDARIO(CALENDARIO_KEY)
);

CREATE TABLE FACT_CALIFICACION (
      CALIFICACION_KEY INT PRIMARY KEY IDENTITY(1,1)
    , ALUMNO_KEY INT
    , ALUMNO_NOMBRES NVARCHAR(255) DEFAULT '?'
    , ALUMNO_APELLIDOS NVARCHAR(255) DEFAULT '?'
    , DOCENTE_KEY INT
    , ASIGNATURA_KEY INT
    , CURSO_DETALLE CHAR(2)
    , NIVEL TINYINT
    , SEMESTRE_KEY INT
    , CALENDARIO_KEY INT
    , NOTA DECIMAL(3,2) DEFAULT 0.00
    , PONDERACION DECIMAL(3,2) DEFAULT 0.00

    , CONSTRAINT FK_NOTA_ALUMNO FOREIGN KEY (ALUMNO_KEY) REFERENCES DIM_ALUMNO(ALUMNO_KEY)
    , CONSTRAINT FK_NOTA_DOCENTE FOREIGN KEY (DOCENTE_KEY) REFERENCES DIM_DOCENTE(DOCENTE_KEY)
    , CONSTRAINT FK_NOTA_ASIGNATURA FOREIGN KEY (ASIGNATURA_KEY) REFERENCES DIM_ASIGNATURA(ASIGNATURA_KEY)
    , CONSTRAINT FK_NOTA_SEMESTRE FOREIGN KEY (SEMESTRE_KEY) REFERENCES DIM_SEMESTRE(SEMESTRE_KEY)
    , CONSTRAINT FK_NOTA_CALENDARIO FOREIGN KEY (CALENDARIO_KEY) REFERENCES DIM_CALENDARIO(CALENDARIO_KEY)
);

CREATE TABLE FACT_ASISTENCIA (
      ASISTENCIA_KEY INT PRIMARY KEY IDENTITY(1,1)
    , ALUMNO_KEY INT
    , ALUMNO_NOMBRES NVARCHAR(255) DEFAULT '?'
    , ALUMNO_APELLIDOS NVARCHAR(255) DEFAULT '?'
    , CURSO_KEY INT
    , CURSO_DETALLE CHAR(2)
    , NIVEL TINYINT
    , CALENDARIO_KEY INT
    , MES VARCHAR(10)
    , DIA VARCHAR(9)
    , HORA_ENTRADA TIME DEFAULT '00:00:00'
    , PRESENTE BIT DEFAULT 1
    , JUSTIFICADO BIT DEFAULT 0

    , CONSTRAINT FK_ASISTENCIA_ALUMNO FOREIGN KEY (ALUMNO_KEY) REFERENCES DIM_ALUMNO(ALUMNO_KEY)
    , CONSTRAINT FK_ASISTENCIA_CURSO FOREIGN KEY (CURSO_KEY) REFERENCES DIM_CURSO(CURSO_KEY)
    , CONSTRAINT FK_ASISTENCIA_CALENDARIO FOREIGN KEY (CALENDARIO_KEY) REFERENCES DIM_CALENDARIO(CALENDARIO_KEY)
);