-- =========================
-- DROP TABLES (ORDEN CORRECTO)
-- =========================

DROP TABLE IF EXISTS FACT_ASISTENCIA;
DROP TABLE IF EXISTS FACT_CALIFICACION;
DROP TABLE IF EXISTS FACT_MATRICULA;

DROP TABLE IF EXISTS DIM_CALENDARIO;
DROP TABLE IF EXISTS DIM_SEMESTRE;
DROP TABLE IF EXISTS DIM_CURSO;
DROP TABLE IF EXISTS DIM_ASIGNATURA;
DROP TABLE IF EXISTS DIM_DOCENTE;
DROP TABLE IF EXISTS DIM_ALUMNO;
DROP TABLE IF EXISTS DIM_COLEGIO;

-- =========================
-- DIMENSIONES
-- =========================

CREATE TABLE DIM_COLEGIO (
      COLEGIO_KEY INT PRIMARY KEY IDENTITY(1,1)
    , NOMBRE_COLEGIO VARCHAR(100) DEFAULT '?'
    , DIRECCION_COLEGIO VARCHAR(200) DEFAULT '?'
    , COMUNA_COLEGIO VARCHAR(50) DEFAULT '?'
);

CREATE TABLE DIM_ALUMNO (
      ALUMNO_KEY INT PRIMARY KEY IDENTITY(1,1)
    , RUT_ALUMNO VARCHAR(12) DEFAULT '?'
    , NOMBRES VARCHAR(70) DEFAULT '?'
    , APELLIDO_PATERNO VARCHAR(50) DEFAULT '?'
    , APELLIDO_MATERNO VARCHAR(50) DEFAULT '?'
    , FECHA_NACIMIENTO NVARCHAR(255) DEFAULT '1900-01-01 00:00:00.000'
    , GENERO VARCHAR(20) DEFAULT '?'
);

CREATE TABLE DIM_DOCENTE (
      DOCENTE_KEY INT PRIMARY KEY IDENTITY(1,1)
    , RUT_DOCENTE VARCHAR(12) DEFAULT '?'
    , NOMBRES VARCHAR(70) DEFAULT '?'
    , APELLIDO_PATERNO VARCHAR(50) DEFAULT '?'
    , APELLIDO_MATERNO VARCHAR(50) DEFAULT '?'
    , ESPECIALIDAD VARCHAR(100) DEFAULT '?'
);

CREATE TABLE DIM_ASIGNATURA (
      ASIGNATURA_KEY INT PRIMARY KEY IDENTITY(1,1)
    , NOMBRE_ASIGNATURA VARCHAR(100) DEFAULT '?'
    , AREA_CONOCIMIENTO VARCHAR(50) DEFAULT '?'
);

CREATE TABLE DIM_CURSO (
      CURSO_KEY INT PRIMARY KEY IDENTITY(1,1)
    , NOMBRE_CURSO VARCHAR(50) DEFAULT '?'
    , NIVEL_EDUCATIVO VARCHAR(50) DEFAULT '?'
);

CREATE TABLE DIM_SEMESTRE (
      SEMESTRE_KEY INT PRIMARY KEY IDENTITY(1,1)
    , NOMBRE_SEMESTRE VARCHAR(50) DEFAULT '?'
    , ANIO_ACADEMICO INT DEFAULT 0
);

CREATE TABLE [dbo].[DIM_CALENDARIO] (
      [CALENDARIO_KEY] INT PRIMARY KEY -- Recomendado: Formato YYYYMMDD (Ej: 20260425)
    , [FECHA_COMPLETA] DATE DEFAULT '1900-01-01' -- Mejor DATE que NVARCHAR para cálculos
    , [DIA_SEMANA] VARCHAR(15) DEFAULT '?'
    , [DIA_MES] INT DEFAULT 0
    , [MES_NOMBRE] VARCHAR(15) DEFAULT '?'
    , [MES_NUMERO] INT DEFAULT 0 -- CRÍTICO: Para que Power BI no ordene los meses alfabéticamente
    , [ANIO] INT DEFAULT 0
    , [ES_FERIADO] BIT DEFAULT 0
    , [ES_DIA_HABIL] BIT DEFAULT 1
);

-- =========================
-- FACTS
-- =========================

CREATE TABLE FACT_MATRICULA (
      MATRICULA_KEY INT PRIMARY KEY IDENTITY(1,1)
    , COLEGIO_KEY INT
    , ALUMNO_KEY INT
    , CURSO_KEY INT
    , CALENDARIO_KEY INT
    , MONTO_MATRICULA DECIMAL(18,2) DEFAULT 0.00
    , NIVEL INT

    , CONSTRAINT FK_MATRICULA_COLEGIO FOREIGN KEY (COLEGIO_KEY) REFERENCES DIM_COLEGIO(COLEGIO_KEY)
    , CONSTRAINT FK_MATRICULA_ALUMNO FOREIGN KEY (ALUMNO_KEY) REFERENCES DIM_ALUMNO(ALUMNO_KEY)
    , CONSTRAINT FK_MATRICULA_CURSO FOREIGN KEY (CURSO_KEY) REFERENCES DIM_CURSO(CURSO_KEY)
    , CONSTRAINT FK_MATRICULA_CALENDARIO FOREIGN KEY (CALENDARIO_KEY) REFERENCES DIM_CALENDARIO(CALENDARIO_KEY)
);

CREATE TABLE FACT_CALIFICACION (
      CALIFICACION_KEY INT PRIMARY KEY IDENTITY(1,1)
    , ALUMNO_KEY INT
    , DOCENTE_KEY INT
    , ASIGNATURA_KEY INT
    , SEMESTRE_KEY INT
    , CALENDARIO_KEY INT
    , NOTA DECIMAL(3,2) DEFAULT 0.00
    , PONDERACION DECIMAL(3,2) DEFAULT 0.00

    , CONSTRAINT FK_NOTA_ALUMNO FOREIGN KEY (ALUMNO_KEY) REFERENCES DIM_ALUMNO(ALUMNO_KEY)
    , CONSTRAINT FK_NOTA_DOCENTE FOREIGN KEY (DOCENTE_KEY) REFERENCES DIM_DOCENTE(DOCENTE_KEY)
    , CONSTRAINT FK_NOTA_ASIGNATURA FOREIGN KEY (ASIGNATURA_KEY) REFERENCES DIM_ASIGNATURA(ASIGNATURA_KEY)
    , CONSTRAINT FK_NOTA_SEMESTRE FOREIGN KEY (SEMESTRE_KEY) REFERENCES DIM_SEMESTRE(SEMESTRE_KEY)
    , CONSTRAINT FK_NOTA_CALENDARIO FOREIGN KEY (CALENDARIO_KEY) REFERENCES DIM_CALENDARIO(CALENDARIO_KEY)
);

CREATE TABLE FACT_ASISTENCIA (
      ASISTENCIA_KEY INT PRIMARY KEY IDENTITY(1,1)
    , ALUMNO_KEY INT
    , CURSO_KEY INT
    , CALENDARIO_KEY INT
    , HORA_ENTRADA TIME DEFAULT '00:00:00'
    , PRESENTE BIT DEFAULT 1
    , JUSTIFICADO BIT DEFAULT 0

    , CONSTRAINT FK_ASISTENCIA_ALUMNO FOREIGN KEY (ALUMNO_KEY) REFERENCES DIM_ALUMNO(ALUMNO_KEY)
    , CONSTRAINT FK_ASISTENCIA_CURSO FOREIGN KEY (CURSO_KEY) REFERENCES DIM_CURSO(CURSO_KEY)
    , CONSTRAINT FK_ASISTENCIA_CALENDARIO FOREIGN KEY (CALENDARIO_KEY) REFERENCES DIM_CALENDARIO(CALENDARIO_KEY)
);