USE [RAW_DATA_ALCANTARA]
GO

INSERT INTO [dbo].[DIM_DOCENTE] (RUT_DOCENTE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES
-- DEPARTAMENTO DE MATEMATICA
  ('12345678-9', 'RICARDO ANTONIO', 'TAPIA', 'SILVA', 'MATEMATICA')
, ('13.456.789-0', '  MONICA DEL CARMEN  ', 'PAREDES', 'RIVAS', 'MATEMATICA')
, ('145678901', 'jorge luis', 'OSSANDON', 'MOYA', 'MATEMATICA')

-- DEPARTAMENTO DE LENGUAJE
, ('11234567-K', 'ELSA PATRICIA', 'VALENZUELA', 'UBILLA', 'LENGUAJE')
, ('15678901-2', '  CARLOS MAURICIO', 'ITURRA', 'GOMEZ', 'LENGUAJE')
, ('10.987.654-3', 'sandra elizabeth', 'OYARZUN', 'DIAZ', 'LENGUAJE')

-- DEPARTAMENTO DE CIENCIAS
, ('12.876.543-2', 'ROBERTO SEGUNDO', 'VENEGAS', 'PARRA', 'CIENCIAS - BIOLOGIA')
, ('14987654-1', 'MARIA CRISTINA', 'JARA', 'VERGARA', 'CIENCIAS - QUIMICA')
, ('16.123.456-7', 'HERNAN RODRIGO', 'POBLETE', 'SALAZAR', 'CIENCIAS - FISICA')

-- DEPARTAMENTO DE INGLES
, ('17.234.567-8', 'CLAUDIA PAOLA', 'FUENTES', 'HENRIQUEZ', 'INGLES')
, ('153456789', 'SERGIO ANDRES', 'ARRIAGADA', 'SOTO', 'INGLES')

-- DEPARTAMENTO DE HISTORIA Y CIENCIAS SOCIALES
, ('13876543-K', 'LORENA ALEJANDRA', 'FIGUEROA', 'CASTRO', 'HISTORIA Y GEOGRAFIA')
, ('11.765.432-1', 'FELIPE IGNACIO', 'CORTES', 'NAVARRETE', 'HISTORIA Y GEOGRAFIA')

-- DEPARTAMENTO DE EDUCACION FISICA
, ('10123456-7', '  CRISTIAN EDUARDO', 'VILLALOBOS', 'TORRES', 'EDUCACION FISICA')
, ('12345123-4', 'VERONICA BEATRIZ', 'MANRIQUEZ', 'MORA', 'EDUCACION FISICA')

-- DEPARTAMENTO DE ARTES Y MUSICA
, ('16789123-5', 'GABRIELA SOLEDAD', 'ALDUNATE', 'VICUÑA', 'ARTES VISUALES')
, ('14.111.222-3', 'JAIME MARCELO', 'RUZ', 'CERDA', 'MUSICA')

-- OTROS DEPARTAMENTOS
, ('15.555.666-7', 'ESTEBAN PATRICIO', 'LAGOS', 'MIÑO', 'FILOSOFIA')
, ('18123123-0', '  ANDREA DEL PILAR  ', 'MIRANDA', 'SANDOVAL', 'TECNOLOGIA');