USE RAW_DATA_ALCANTARA
GO

SET LANGUAGE Spanish;
SET DATEFIRST 1; -- Forzamos que Lunes = 1, Sábado = 6, Domingo = 7

DECLARE @FECHA_INICIO DATE = '2025-01-01';
DECLARE @FECHA_FIN DATE = '2026-12-31';
DECLARE @FECHA_PROCESO DATE = @FECHA_INICIO;

WHILE @FECHA_PROCESO <= @FECHA_FIN
BEGIN
    DECLARE @CALENDARIO_KEY INT = CAST(CONVERT(VARCHAR(8), @FECHA_PROCESO, 112) AS INT);
    DECLARE @DIA_SEMANA_NOMBRE VARCHAR(20) = UPPER(DATENAME(WEEKDAY, @FECHA_PROCESO));
    DECLARE @MES_NOMBRE VARCHAR(20) = UPPER(DATENAME(MONTH, @FECHA_PROCESO));
    DECLARE @ES_FERIADO BIT = 0;
    DECLARE @ES_DIA_HABIL BIT = 1;

    -- Lógica de Feriados
    IF (MONTH(@FECHA_PROCESO) = 1 AND DAY(@FECHA_PROCESO) = 1)
       OR (MONTH(@FECHA_PROCESO) = 5 AND DAY(@FECHA_PROCESO) = 1)
       OR (MONTH(@FECHA_PROCESO) = 5 AND DAY(@FECHA_PROCESO) = 21)
       OR (MONTH(@FECHA_PROCESO) = 9 AND DAY(@FECHA_PROCESO) IN (18, 19))
       OR (MONTH(@FECHA_PROCESO) = 12 AND DAY(@FECHA_PROCESO) = 25)
    BEGIN
        SET @ES_FERIADO = 1;
    END

    -- Lógica de Día Hábil CORREGIDA
    -- Con DATEFIRST 1: Sábado es 6 y Domingo es 7
    IF DATEPART(WEEKDAY, @FECHA_PROCESO) IN (6, 7) OR @ES_FERIADO = 1 
    BEGIN
        SET @ES_DIA_HABIL = 0;
    END

    INSERT INTO [dbo].[DIM_CALENDARIO] (
          [CALENDARIO_KEY]
        , [FECHA_COMPLETA]
        , [DIA_SEMANA]
        , [MES_NOMBRE]
        , [ES_DIA_HABIL]
        , [ES_FERIADO]
    ) VALUES (
          @CALENDARIO_KEY
        , CAST(@FECHA_PROCESO AS NVARCHAR(255))
        , @DIA_SEMANA_NOMBRE
        , @MES_NOMBRE
        , @ES_DIA_HABIL
        , @ES_FERIADO
    );

    SET @FECHA_PROCESO = DATEADD(DAY, 1, @FECHA_PROCESO);
END
GO

SELECT TOP 10 * FROM DIM_CALENDARIO